# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Do_Did_List' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!
  use_modular_headers!

  # Pods for Do_Did_List
  pod 'SideMenu'

end
